### ISSUE TITLE
[minimal] Network manager does not request wifi password

### ISSUE THREAD

**Issue by mdickie** [Antergos/Cnchi#326]
Trying to choose a network but network manager doesn't seem to request password.

**Comment by karasu** [comment]
Which ISO did you use? (minimal or standard, and date, please).

**Comment by mdickie** [comment]
Minimal

**Comment by mdickie** [comment]
Yesterday

**Comment by mdickie** [comment]
Live iso just works.

**Comment by axaxs** [comment]
This used to be caused by gnome-keyring not being installed.  Are we not including it in minimal?

**Comment by lots0logs** [comment]
This should be fixed in the latest testing builds. I'd like to do a iso release as soon as we can verify the images are working properly. Especially GNOME screen locking.

**Comment by karasu** [comment]
This should go into antergos-iso repository. Closing.

**Comment by Mikaela** [comment]
I am havint this with base-installed Antergos and I don't think this is only related to the iso.

To add password,  you first attempt to connect to the network, then go to edit connections and edit the connection and write the encryption key there.

**Comment by lots0logs** [comment]
@Mikaela I believe you are reporting a different issue. Correct me if I am wrong, but your issue is one that occurs after the installation on your installed system, no?

**Comment by Mikaela** [comment]
@lots0logs I believe this is the same issue and something related to network manager rather than the isos and yes, I am using installed system, but is there difference in network-manager in the ISO and installed system?

**Comment by lots0logs** [comment]
Well, in this particular case the issue was with an missing configuration file on the Minimal ISO. The main ISO is basically the same as an installed system, but there are a few differences. One of which is that the ISOs have a keyring for the antergos user account configured. For an installed system the user must initialize their own keyring (I'm talking about gnome-keyring, not pacman) when prompted by GNOME. 

Its been over ya year since I looked into it so it may be different now BUT at that time setting up the keyring for gnome-keyring programmatically was not possible (it required user interaction). We can look into it again if need be. Though we'll need to open a new issue as this issue is not the same and was already fixed and closed.  Let me know if you have any questions. Thanks!

**Comment by Mikaela** [comment]
I see. This issue that I am having isn't so big issue to me as I must visit the connection editor anyway to enable IPv6 privacy extensions and I don't connect to new networks daily.

**Comment by zotherstupidguy** [comment]
just installed minimal 64 iso and faced this as well; had to edit the configurations manually.

**Comment by AssailantLF** [comment]
Just attempted to install via the Minimal ISO, shown on the downloads page. Pretty dumb that this has been a problem for **months**

I agree with what aequis said:

>Incredibly annoying that the first thing I need to do when trying to use a supposedly easy-to-install distro is google for a fix for a problem that, apparently, has existed for months. This isn't user friendly.

This trivial-seeming bug should be fixed, because it really deters new users who haven't tried the distro before, or are unfamiliar with Linux.

"Antergos? Don't try it, because it won't even let you input your wifi password without a terminal command"

**Comment by lots0logs** [comment]
I have tried to reproduce this issue several times. It works fine for me. If we cannot reproduce the issue then we cannot fix it. Sorry!

**Comment by mdickie** [comment]
I don't mind closing this issue, I don't use Antergos anymore. I am now happy with Arch Linux. Thx for trying to reproduce it.

**Comment by ufukuyumaz** [comment]
Same issue still exist. I cant even edit settings manually all fields locked.

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-iso/issues/28#issuecomment-285865232

**Comment by ipedrazas** [comment]
The issue still exists. `nmtui` allows you to manually connect though.
