### ISSUE TITLE
Mouse cursor invisible in installer

### ISSUE THREAD

**Issue by jpambrun** [Antergos/Cnchi#709]
### Problem:
In the installer (both live and minimal ISOs) the mouse cursor is visually stuck in the top-left corner, but the cursor acts like if it was moving (highlights UI elements, context menu, etc.). 

This makes it impossible to install.

### Steps To Reproduce:

On my setup..

1. Boot live/minimal iso.
2. Move mouse.
3. Notice no cursor movement.

### Log Files
N/A

### Additional Notes:
UEFI
NVIDIA GTX1080

I have tried almost any combination of noacpi, nokms, nomodeset, modeprobe.blacklist=nouveau and orthers that I forgot, but the result is always either 1- invisible cursor or 2- no screen found.

Manjaro's live CD works fine.

I can try workaround/fix suggestions and report back.

**Comment by iNZIGHT** [comment]
Having the same problem with a GTX 1070. 
Tried the above. Also tried burning new iso, with same result. No mouse, or no screen :/

**Comment by terriblespider** [comment]
Have you changed the noacpi at the GRUB menu or by changing the kernel mode to "noacpi"?
Just changing the kernel mode at the start fixed it for me.
After the installation I could go forward following the Antergos guide for this error:
https://antergos.com/wiki/hardware/graphics/invisible-mouse-cursor/

**Comment by iNZIGHT** [comment]
No since I've do not have any GRUB menu, a.k.a have not installed it yet since I kinda need my mouse to click through the menus on the installer.

I've tried the noacpi kernel mode in the antergos menu before booting into the live environment which causes a blackscreen. Same for nomodeset. nouveau.modeset=0 or nouveau.blacklist=1 Does not work either.

**Comment by stratus-ss** [comment]
I tagged this as needs testing. I wasn't able to reproduce this on my GTX 970. It could be something with the newer video card and the open source drivers?

**Comment by iNZIGHT** [comment]
Possiby. I for one think its located with the nouveau driver. Since today I ran the plain arch installer and installed the nvidia package with no issues. 

A possible fix would be to mount the live iso and chroot to it and replace the nouveau driver with nvidia one.. Maybe, i'll try that tomorrow.

**Comment by jpambrun** [comment]
I am adding some information in order to help diagnosing this issue.

First, this it what I mean by invisible mouse cursor. 
https://dl.dropboxusercontent.com/u/168338/IMG_20170218_111935.jpg
In this example, I can click on "create new panel", all UI respond correctly to mouse inputs, but the displayed cursor just won't move from the upper left corner of the screen.
I get this behavior with the default "Antergos x86_64" boot option in the UEFI bootloaded .

With the "NVIDIA fallback", I get the following Xorg.0.log;
https://dl.dropboxusercontent.com/u/168338/IMG_20170218_111715.jpg

These are the kernel options associated with this menu entry:
https://dl.dropboxusercontent.com/u/168338/IMG_20170218_111822.jpg

**Comment by jpambrun** [comment]
Actually, this was from the minimal ISO.

From the Live ISO, with nouveau.blacklist=1, I get 
https://dl.dropboxusercontent.com/u/168338/IMG_20170218_123853.jpg

the nvidia fallback give a single blinking '_', Idem for just 'nomodeset'.

**Comment by stratus-ss** [comment]
Thanks for the screenshots. You can see that for sure this is related to the newer GPUs as there is an "unknown chipset NV134" error on the screen. It is possible that we may need to use a git version of mesa or xf86-video-nouveau.

I have an active interest in a fix/workaround for this as I plan to buy an 1060 or 1070 in the next month or two. Thanks for updating

@lots0logs @karasu any thoughts on how to proceed with this?

**Comment by lots0logs** [comment]
It takes at least a few months for new chips to be supported by nouveau. For those chips, the NVIDIA driver needs to be used. What I'd like to do is configure the iso to fallback to the NVIDIA drivers when X fails  using an NVIDIA card. I havent come up with a solid plan for this yet, but I have a couple of ideas (just need to do some testing to see what will work and what wont)

**Comment by stratus-ss** [comment]
The OP reported that Manjero some how solved this. I wonder how they did it

**Comment by howdoicomputer** [comment]
So I came across the same bug on my GTX 1060 driven machine so I am installing Manjaro to try that out.

@stratus-ss They get around it by having a GRUB entry that loads non-free drivers. I believe they also have a text only install; that may work as well since you'd be able to install the proprietary driver during the installation process.

**Comment by iNZIGHT** [comment]
Can confirm that manjaro works with my GTX 1070.

**Comment by michael1011** [comment]
I have the same problem here with my GTX 1070. Has anyone found a solution yet?

**Comment by howdoicomputer** [comment]
@michael1011 I never found a solution so I switched to Manjaro.

**Comment by iNZIGHT** [comment]
Same. Do not got time to however mount the live distro and chroot to it, and then install NVIDIA, @michael1011  try that maybe?

**Comment by stratus-ss** [comment]
I marked this as a bug. I wanted to put this with higher priority but I don't think 'critical' is appropriate. I wish there was another label i had that was between non-critical and critical

**Comment by jpambrun** [comment]
Since the major appeal of Antergos is easier installation I have proceeded to installed vanilla Arch for now.

I will likely come try again next time I need to install.
I the meantime, I can still try live isos/kernels options if needed.

Thanks for the good work.

**Comment by michael1011** [comment]
I tried to edit the ISO file twice but I failed (it did not boot). So I did the same like @jpambrun and installed vanilla Arch which works fine with Nvidia drivers.

**Comment by howdoicomputer** [comment]
I think a big problem is a relative inflexibility of how Antergos is installed; a text based installer would offer a way to circumvent this problem.

**Comment by Yoshi2889** [comment]
This is a bug in nouveau, not Antergos: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1646574

The live ISO should have the same issues. Try using the nvidia fallback.

**Comment by jpambrun** [comment]
I don't think it is appropriate to close this issue, at least for tracking purposes, unless there is a workaround. The nvidia fallback didn't work last time I tried and there was no way to install Antergos, at all.

That said, I don't feel very strongly about this issue anymore since I had no choice but to move to another Linux solution.

**Comment by iNZIGHT** [comment]
@Yoshi2889 yeah cause we've not tried the nvidia fallback x number of times.

I second @jpambrun, the issue should not be closed @karasu.
For the rest who still have the issue, move to manjaro or something better with loadable nvidiadrivers at boot.

**Comment by karasu** [comment]
@jpambrun There is a dev version of antergos-iso in the works that should solve this one (letting you select nvidia proprietary drivers), I'll get back to you when it's ready.

Anyways, when nouveau supports this the issue will be gone.

**Comment by jpambrun** [comment]
I understand that this issue will be fixed once nouveau supports the 10xx
series and the ISO is updated, but it is possible that the next series will
break the installer again.

Great news about the proprietary drivers.
Keep up the good work!

**Comment by Yoshi2889** [comment]
@iNZIGHT No need to get snappy, telling users to move to a different distribution is not an acceptable answer. This issue is being worked on.

@jpambrun The issue is being fixed by the Nouveau team and will land in the kernel, upon which Antergos will pick it up from the Arch repositories. When all of that happens, no idea; I don't think it's fixed already.

**Comment by Yoshi2889** [comment]
Looks like kernel 4.10 contains the fix, and that has already landed in Arch. So an ISO update should fix this issue.

**Comment by iNZIGHT** [comment]
@Yoshi2889 Yeah, sorry bout that. Just felt that "try using the nvidia fallback" was kinda redundant cause in my head that is the first thing you try to do if you have a new NVIDIA card.  Moving to another distro in the mean time IS an acceptable answer. Users who want to try antergos and use it for a while but is not able to install this due to the bug will most likely move to something else. I for one did this, but will probably test Antergos again when the ISO update hits :)

**Comment by jpambrun** [comment]
In all fairness, I was also perplexed (maybe even a bit insulted) by the "try using the nvidia fallback".. You know, I would not have gone through all that trouble if the only obvious thing worked.. 

Also, when facing this issue, installing another distro is the only thing that can get Linux on your computer.. so it's really the only applicable advice.

Again, with that said, I really appreciate your efforts and commitment. Keep it up!

**Comment by Yoshi2889** [comment]
I agree it is obvious, but it is worth mentioning.

Although instead of switching distros workarounds can be searched for or the issue can be investigated, hence why I think it is a bad suggestion and bad advice.

Anyway, lets not argue in what is an issue discussion and lets focus on the problem at hand.

**Comment by Yoshi2889** [comment]
So with the new ISO being released, this issue is probably fixed. Anyone
able to confirm?

**Comment by ccavanaugh** [comment]
I tried the antergos-17.4-x86_64.iso on the 5th and had the issue with the missing cursor using a GTX 1060. 

Attempts to use the Nvida fallback would result in a failure to boot the iso with an error seeming to indicate the kernel could not be found.  Will try again soon to capture the exact error.

**Comment by rockybulwinkle** [comment]
I'm having an issue with my mouse cursor not showing up on my macbook pro retina 13", late 2015. It has intel iris graphics though, not nvidia. Is this the right place for this issue or should a new one be opened for intel graphics?

**Comment by rockybulwinkle** [comment]
I managed to fix it. What I did was take the fix here: https://antergos.com/wiki/hardware/graphics/invisible-mouse-cursor/

I unpacked the iso and squashfs, added that fix above into the X11 conf, repacked the squashfs, updated the squashfs md5, partitioned my usb disk for the ANTERGOS partition (I made it ext3 even though originally it was iso9660), made my EFI partition, and copied all the files over. It works like a charm ^_^.

**Comment by Ulrik-dk** [comment]
This is still an issue in 2019, with the latest ISO. Attempting to use "Nvidia fallback" results in a login-screen that directs the user to find help in the forums. I'm also trying out Manjaro now.
